const PRODUCTOS_DEFAULT = [
  { "id": "cuarto", "nombre": "1/4 KG", "precio": 4500 },
  { "id": "medio", "nombre": "1/2 KG", "precio": 8000 },
  { "id": "kilo", "nombre": "1 KG", "precio": 14500 },
  { "id": "vaso", "nombre": "Vaso", "precio": 3000 },
  { "id": "cucurucho", "nombre": "Cucurucho", "precio": 3500 },
  { "id": "conodoble", "nombre": "Cono doble", "precio": 5000 }
];

let productos = JSON.parse(localStorage.getItem('productos_config') || 'null') || PRODUCTOS_DEFAULT;
let carrito = [];
let ventas = JSON.parse(localStorage.getItem('ventas_mes') || '[]');
const HOY = new Date().toLocaleDateString();
let COMISION_PY = Number(localStorage.getItem('comisionPY') || 35);

function getMesAnio(fechaStr){ try{ let parts = fechaStr.split('/'); return {m: parseInt(parts[1]), a: parseInt(parts[2])}; }catch(e){ return {m: new Date().getMonth()+1, a: new Date().getFullYear()}; } }

function init(){
  let negocio = localStorage.getItem('negocio_nombre');
  let nombre = localStorage.getItem('vendedor_nombre');
  let tienePrecios = localStorage.getItem('productos_config');
  const b = document.getElementById('bienvenida'); const a = document.getElementById('app'); const p1 = document.getElementById('paso1'); const p2 = document.getElementById('paso2'); const p3 = document.getElementById('paso3');
  let nombreMostrar = negocio? negocio.toUpperCase() : "TU HELADERÍA";
  document.getElementById('tituloBienvenida').innerText = nombreMostrar;
  document.getElementById('subBienvenida').innerText = negocio || "Sistema de Ventas";
  document.getElementById('brandTop').innerText = nombreMostrar;
  document.title = negocio? `${nombreMostrar} - Ventas` : "Heladería - Sistema de Ventas";
  if(negocio && nombre && tienePrecios){ b.style.display='none'; a.style.display='block'; document.getElementById('saludo').innerText=`Turno: ${nombre}`; render(); }
  else if(negocio && nombre &&!tienePrecios){ b.style.display='flex'; a.style.display='none'; p1.style.display='none'; p2.style.display='none'; p3.style.display='block'; renderPasoPrecios(); }
  else if(negocio &&!nombre){ b.style.display='flex'; a.style.display='none'; p1.style.display='none'; p2.style.display='block'; p3.style.display='none'; }
  else { b.style.display='flex'; a.style.display='none'; p1.style.display='block'; p2.style.display='none'; p3.style.display='none'; }
  cargarProductos();
  document.getElementById('btnPY').innerText = `🔴 PEDIDOS YA +${COMISION_PY}%`;
  document.getElementById('btnPY').onclick = () => cobrar('PEDIDOSYA');
}

// CARGA LIMPIA - SIN JSON EXTERNO
function cargarProductos(){
  let guardados = JSON.parse(localStorage.getItem('productos_config') || 'null');
  if (!guardados) {
    productos = PRODUCTOS_DEFAULT;
  } else {
    productos = guardados;
    // Si agregas un producto nuevo en el DEFAULT, se suma sin pisar precios editados
    PRODUCTOS_DEFAULT.forEach(def => {
      if (!productos.find(p => p.id === def.id)) productos.push(def);
    });
  }
  renderBotones();
}

function renderPasoPrecios(){ const cont = document.getElementById('listaPreciosConfig'); cont.innerHTML = ''; productos.forEach(p=>{ cont.innerHTML += `<div class="precio-row"><label>${p.nombre}</label><input type="number" id="precio_${p.id}" value="${p.precio}" inputmode="numeric"></div>`; }); }
function guardarPrecios(){ let nuevos = []; productos.forEach(p=>{ let val = Number(document.getElementById(`precio_${p.id}`).value) || 0; nuevos.push({id: p.id, nombre: p.nombre, precio: val}); }); productos = nuevos; localStorage.setItem('productos_config', JSON.stringify(productos)); if(localStorage.getItem('vendedor_nombre')){ document.getElementById('bienvenida').style.display='none'; document.getElementById('app').style.display='block'; document.getElementById('saludo').innerText=`Turno: ${localStorage.getItem('vendedor_nombre')}`; render(); renderBotones(); } else { guardarNombre(); } }
function editarPrecios(){ if(confirm('¿Editar precios?')){ localStorage.removeItem('productos_config'); productos = PRODUCTOS_DEFAULT; document.getElementById('app').style.display='none'; document.getElementById('bienvenida').style.display='flex'; document.getElementById('paso1').style.display='none'; document.getElementById('paso2').style.display='none'; document.getElementById('paso3').style.display='block'; renderPasoPrecios(); } }
function toggleVentas(){ const body = document.getElementById('contenedorLista'); const btn = document.getElementById('btnToggleVentas'); body.classList.toggle('open'); btn.innerText = body.classList.contains('open')? '▲ Ocultar' : '▼ Ver ventas'; if(body.classList.contains('open')) body.scrollTop = 0; }
function guardarNegocio(){ let n=document.getElementById('negocioInput').value.trim(); if(!n) return; localStorage.setItem('negocio_nombre', n); document.getElementById('paso1').style.display='none'; document.getElementById('paso2').style.display='block'; init(); }
function guardarNombre(){ let n=document.getElementById('nombreInput').value.trim(); if(!n &&!localStorage.getItem('vendedor_nombre')) return; if(n) localStorage.setItem('vendedor_nombre', n); let tienePrecios = localStorage.getItem('productos_config'); if(!tienePrecios){ document.getElementById('paso2').style.display='none'; document.getElementById('paso3').style.display='block'; renderPasoPrecios(); } else { init(); } }
function cambiarUsuario(){ if(confirm('¿Cerrar turno? Esto NO cierra la caja, solo cambia de vendedor')){ localStorage.removeItem('vendedor_nombre'); location.reload(); } }
function cambiarNegocio(){ if(confirm('¿Cambiar nombre del negocio? Se borrarán precios y cierres')){ localStorage.removeItem('negocio_nombre'); localStorage.removeItem('vendedor_nombre'); localStorage.removeItem('productos_config'); localStorage.removeItem('ventas_mes');  localStorage.removeItem('cierres'); location.reload(); } }
function guardar(){ localStorage.setItem('ventas_mes', JSON.stringify(ventas)); render(); }
function renderBotones(){ const cont=document.getElementById('botones'); if(!cont) return; cont.innerHTML=''; productos.forEach(p=>{ let btn=document.createElement('button'); btn.className='prod-btn'; btn.innerText=`${p.nombre}\n$${p.precio.toLocaleString()}`; btn.onclick=()=>seleccionarProducto(p, btn); cont.appendChild(btn); }); }
function seleccionarProducto(p, btn){ btn.classList.add('active'); setTimeout(()=>btn.classList.remove('active'),150); let idx = carrito.findIndex(c=>c.id===p.id); if(idx>=0){ carrito[idx].cant++; } else { carrito.push({id:p.id, nombre:p.nombre, precio:p.precio, cant:1}); } renderCarrito(); }
function renderCarrito(){ const cont = document.getElementById('carrito'); const lista = document.getElementById('carritoLista'); const bloque = document.getElementById('bloqueCobro'); const preview = document.getElementById('previewPY'); if(carrito.length===0){ cont.style.display='none'; bloque.style.display='none'; preview.style.display='none'; return; } cont.style.display='block'; bloque.style.display='block'; lista.innerHTML=''; let total=0; carrito.forEach((item,i)=>{ let sub = item.precio*item.cant; total+=sub; lista.innerHTML+=`<div class="carrito-item"><div><b>${item.nombre}</b></div><div class="qty"><button onclick="cambiarCant(${i},-1)">−</button><span style="min-width:20px;text-align:center;font-weight:800">${item.cant}</span><button class="plus" onclick="cambiarCant(${i},1)">+</button><b style="color:var(--naranja);margin-left:8px;min-width:60px;text-align:right">$${sub.toLocaleString()}</b></div></div>`; }); document.getElementById('carritoTotal').innerText='$'+total.toLocaleString(); let recargo = Math.round(total * COMISION_PY / 100); preview.style.display='block'; preview.innerHTML = `Si cobrás por Pedidos Ya: <b>$${total.toLocaleString()} + $${recargo.toLocaleString()} = $${(total+recargo).toLocaleString()}</b>`; }
function cambiarCant(index, delta){ carrito[index].cant+=delta; if(carrito[index].cant<=0) carrito.splice(index,1); renderCarrito(); }
function vaciarCarrito(){ carrito=[]; renderCarrito(); }
function cobrar(metodo){ if(carrito.length===0) return; let esPY = metodo==='PEDIDOSYA'; carrito.forEach(item=>{ for(let k=0;k<item.cant;k++){ ventas.push({ f: HOY, h: new Date().toLocaleTimeString(), p: item.nombre, vBase: item.precio, vComision: esPY? Math.round(item.precio * COMISION_PY / 100) : 0, vFinal: item.precio + (esPY? Math.round(item.precio * COMISION_PY / 100) : 0), v: item.precio, metodo: metodo, vendedor: localStorage.getItem('vendedor_nombre') }); } }); guardar(); carrito=[]; renderCarrito(); }
function cerrarTurno(){ let ventasHoy = window._ventasHoy || []; if(ventasHoy.length===0){ alert('No hay ventas en este turno para cerrar'); return; } let bruto = ventasHoy.reduce((a,b)=>a+(b.vFinal||b.v),0); let com = ventasHoy.reduce((a,b)=>a+(b.vComision||0),0); let neto = bruto - com; let porMetodo = {}; ventasHoy.forEach(v=>{ let m = v.metodo || 'OTRO'; if(!porMetodo[m]) porMetodo[m]={cant:0,total:0}; porMetodo[m].cant++; porMetodo[m].total+=(v.vFinal||v.v); }); let detalleMetodo = Object.entries(porMetodo).map(([k,v])=>`${k}: ${v.cant} ventas $${v.total.toLocaleString()}`).join('\n'); if(!confirm(`¿CERRAR TURNO?\n\nVendedor: ${localStorage.getItem('vendedor_nombre')}\nFecha: ${HOY}\nVentas: ${ventasHoy.length}\n\nNETO: $${neto.toLocaleString()}\nBRUTO: $${bruto.toLocaleString()}\nCOMISION PY: $${com.toLocaleString()}\n\n${detalleMetodo}\n\nSe exportará el CSV y HOY quedará en 0. El MES seguirá sumando.`)) return; exportarDiario(); let cierres = JSON.parse(localStorage.getItem('cierres') || '[]'); cierres.push({ fecha: HOY, hora: new Date().toLocaleTimeString(), vendedor: localStorage.getItem('vendedor_nombre'), bruto, comision: com, neto, cantidad: ventasHoy.length, porMetodo, ventas: ventasHoy }); localStorage.setItem('cierres', JSON.stringify(cierres)); ventas = ventas.filter(v=> v.f!== HOY); guardar(); alert('✅ Turno cerrado. HOY en 0'); }
function verCierres(){ let cierres = JSON.parse(localStorage.getItem('cierres') || '[]'); if(cierres.length===0){ alert('No hay cierres guardados'); return; } const lista = document.getElementById('listaCierres'); lista.innerHTML = ''; cierres.slice().reverse().forEach((c)=>{ let metodos = Object.entries(c.porMetodo||{}).map(([k,v])=>`${k} $${v.total.toLocaleString()}`).join(' | '); lista.innerHTML += `<div style="background:#111;border:1px solid #232323;border-radius:12px;padding:12px;margin-top:10px"><div style="display:flex;justify-content:space-between"><b style="color:var(--naranja)">${c.fecha} ${c.hora}</b><small style="opacity:.5">${c.vendedor}</small></div><div style="margin-top:6px;font-size:13px">NETO <b>$${c.neto.toLocaleString()}</b> | Bruto $${c.bruto.toLocaleString()} | Com $${c.comision.toLocaleString()}</div><div style="margin-top:4px;font-size:11px;opacity:.6">${c.cantidad} ventas | ${metodos}</div></div>`; }); document.getElementById('modalCierres').classList.add('open'); }
function cerrarModal(){ document.getElementById('modalCierres').classList.remove('open'); }
function render(){ /* igual que antes */ const lista=document.getElementById('lista'); lista.innerHTML=''; let {m: mesActual, a: anioActual} = getMesAnio(HOY); let ventasMesActual = ventas.filter(v=>{ try{ let {m,a}=getMesAnio(v.f); return m===mesActual && a===anioActual;}catch(e){return true;} }); let ventasHoy = ventasMesActual.filter(v=>v.f === HOY); let brutoHoy = ventasHoy.reduce((a,b)=>a+(b.vFinal||b.v),0); let comisionHoy = ventasHoy.reduce((a,b)=>a+(b.vComision||0),0); let netoHoy = brutoHoy - comisionHoy; let cierres = JSON.parse(localStorage.getItem('cierres') || '[]'); let cierresMes = cierres.filter(c=>{ try{ let {m,a}=getMesAnio(c.fecha); return m===mesActual && a===anioActual; }catch(e){return true;} }); let brutoCierresMes = cierresMes.reduce((a,b)=>a+b.bruto,0); let comCierresMes = cierresMes.reduce((a,b)=>a+b.comision,0); let netoCierresMes = cierresMes.reduce((a,b)=>a+b.neto,0); let cantCierresMes = cierresMes.reduce((a,b)=>a+b.cantidad,0); let totalMesBruto = ventasMesActual.reduce((a,b)=>a+(b.vFinal||b.v),0) + brutoCierresMes; let totalMesComision = ventasMesActual.reduce((a,b)=>a+(b.vComision||0),0) + comCierresMes; let totalMesNeto = totalMesBruto - totalMesComision; let totalCantMes = ventasMesActual.length + cantCierresMes; document.getElementById('totalHoy').innerHTML = `$${netoHoy.toLocaleString()}<div style="font-size:11px;opacity:.6;font-weight:400;margin-top:2px">Bruto: $${brutoHoy.toLocaleString()} | Com: $${comisionHoy.toLocaleString()}</div>`; document.getElementById('cantHoy').innerText= ventasHoy.length + ' ventas (turno actual)'; document.getElementById('totalMes').innerHTML = `$${totalMesNeto.toLocaleString()}<div style="font-size:11px;opacity:.6;font-weight:400;margin-top:2px">Bruto: $${totalMesBruto.toLocaleString()} | Cerrado: $${netoCierresMes.toLocaleString()}</div>`; document.getElementById('cantMes').innerText= totalCantMes + ` ventas 1 al ${HOY.split('/')[0]} (con cierres)`; document.getElementById('info').innerText = `Del 1/${mesActual}/${anioActual} al ${HOY} | Com PY: ${COMISION_PY}% | Cierres mes: ${cierresMes.length}`; if(ventasHoy.length === 0){ lista.innerHTML = `<div style="text-align:center;padding:20px;opacity:.3;font-size:12px">Sin ventas en turno actual<br>Si cerraste turno, está en historial</div>`; } else { ventasHoy.slice().reverse().forEach(x=>{ const tagMetodo = x.metodo? `<span style="font-size:9px;padding:2px 6px;border-radius:10px;background:#222;border:1px solid #333;margin-left:6px">${x.metodo}</span>` : ''; lista.innerHTML+=`<div class=card><span><span style="color:#e9a23b">●</span> ${x.p}${tagMetodo}<br><small style="opacity:.4;font-size:11px">${x.f} ${x.h} ${x.vComision?`+com $${x.vComision}`:''}</small></span><b>$${(x.vFinal||x.v).toLocaleString()}</b></div>`; }); } document.getElementById('tituloVentas').innerText = `VENTAS DEL DÍA (${ventasHoy.length})`; window._ventasMesActual = ventasMesActual; window._ventasHoy = ventasHoy; }
function exportarDiario(){ let negocio = localStorage.getItem('negocio_nombre') || 'HELADERIA'; let nombre = localStorage.getItem('vendedor_nombre'); let ventasHoy = window._ventasHoy || []; if(ventasHoy.length===0){ alert('No hay ventas de hoy'); return; } let brutoHoy = ventasHoy.reduce((a,b)=>a+(b.vFinal||b.v),0); let comisionHoy = ventasHoy.reduce((a,b)=>a+(b.vComision||0),0); let netoHoy = brutoHoy - comisionHoy; let resumen = {}; ventasHoy.forEach(v=>{ if(!resumen[v.p]) resumen[v.p]={c:0,m:0,com:0}; resumen[v.p].c++; resumen[v.p].m+=(v.vFinal||v.v); resumen[v.p].com+=(v.vComision||0); }); let csv = `${negocio.toUpperCase()} - VENTA DIARIA - TURNO\nVendedor,${nombre}\nFecha,${HOY}\nHora cierre,${new Date().toLocaleTimeString()}\n\nTOTAL NETO,$${netoHoy},BRUTO,$${brutoHoy},COMISION,$${comisionHoy}\n\nRESUMEN POR PRODUCTO\nProducto,Cantidad,Total,Comision\n`; Object.entries(resumen).forEach(([p,d])=>{ csv+=`"${p}",${d.c},${d.m},${d.com}\n`; }); csv+=`\nDETALLE\nHora,Producto,Precio Base,Comision,Total,Metodo\n`; ventasHoy.forEach(v=>{ csv+=`${v.h},"${v.p}",${v.vBase||v.v},${v.vComision||0},${v.vFinal||v.v},${v.metodo||''}\n`; }); let blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}); let a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`CIERRE-${negocio}-${nombre}-${HOY.replaceAll('/','-')}-${new Date().toLocaleTimeString().replaceAll(':','-')}-NETO$${netoHoy}.csv`; a.click(); }
function exportarMes(){ let negocio = localStorage.getItem('negocio_nombre') || 'HELADERIA'; let nombre = localStorage.getItem('vendedor_nombre'); let ventasMesActual = window._ventasMesActual || []; let cierres = JSON.parse(localStorage.getItem('cierres') || '[]'); let {m: mesActual, a: anioActual} = getMesAnio(HOY); let cierresMes = cierres.filter(c=>{ try{ let {m,a}=getMesAnio(c.fecha); return m===mesActual && a===anioActual; }catch(e){return true;} }); let todasVentasMes = [...ventasMesActual]; cierresMes.forEach(c=>{ todasVentasMes.push(...(c.ventas||[])); }); if(todasVentasMes.length===0){ alert('No hay ventas este mes'); return; } let brutoMes = todasVentasMes.reduce((a,b)=>a+(b.vFinal||b.v),0); let comMes = todasVentasMes.reduce((a,b)=>a+(b.vComision||0),0); let netoMes = brutoMes - comMes; let {m, a: anio} = getMesAnio(HOY); let resumen = {}; todasVentasMes.forEach(v=>{ if(!resumen[v.p]) resumen[v.p]={c:0,m:0}; resumen[v.p].c++; resumen[v.p].m+=(v.vFinal||v.v); }); let csv = `${negocio.toUpperCase()} - REPORTE MENSUAL (CON CIERRES)\nVendedor,${nombre}\nPeriodo,Del 1/${m}/${anio} al ${HOY}\nNeto,$${netoMes},Bruto,$${brutoMes},Comision,$${comMes}\nCierres incluidos,${cierresMes.length}\n\nRESUMEN POR PRODUCTO\nProducto,Cantidad,Total\n`; Object.entries(resumen).forEach(([p,d])=>{ csv+=`"${p}",${d.c},${d.m}\n`; }); csv+=`\nDETALLE\nFecha,Hora,Producto,Base,Comision,Total,Metodo,Vendedor\n`; todasVentasMes.forEach(v=>csv+=`${v.f},${v.h},"${v.p}",${v.vBase||v.v},${v.vComision||0},${v.vFinal||v.v},${v.metodo||''},${v.vendedor}\n`); let blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}); let aEl=document.createElement('a'); aEl.href=URL.createObjectURL(blob); aEl.download=`MES-COMPLETO-${m}-${anio}-${negocio}-NETO$${netoMes}-${HOY.replaceAll('/','-')}.csv`; aEl.click(); }

if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');
init();